---
- include_role:
    name: microk8s

- include_role:
    name: dt-operator
    
- name: Pause for 2 minutes to allow operator to start
  ansible.builtin.pause:
    minutes: 2
    
- include_role:
    name: app-easytrade

# Include and template use case specific values before installing Dashboard
- set_fact:
    include_dashboard_value_file: "{{ role_path }}/templates/easytravel-dashboard.yml.j2"

- include_role:
    name: dashboard
    tasks_from: template-values-file

- include_role:
    name: dashboard
